[package]
name = "ordslice"
version = "0.1.0"
authors = ["Alkis Evlogimenos <alkis@evlogimenos.com>"]

[lib]
name = "ordslice"
bench = false

[dev-dependencies]
rand = "0.3"

[profile.bench]
opt-level = 3
